# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Prompt
format = '''
[┌─ ](bold green)$username@$hostname:$directory$rust$package$python$docker
[└─►](bold green) '''

[username]
show_always = true
format = '[$user]($style)'

[hostname]
ssh_only = false
format = '[$hostname](bold red)'
trim_at = '.companyname.com'
disabled = false

[directory]
home_symbol = '~'

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = '[x](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = false
